name: lab
include:
  - ./compose/convertx.yaml
  - ./compose/n8n-server.yaml
  - ./compose/npm-proxy.yaml
  - ./compose/stirling-pdf.yaml
  - ./compose/children.yaml
services:
  dev:
    extends:
      file: ./compose/common.yaml
      service: common
    container_name: env
    hostname: env
    environment:
      - CODE_SERVER_PORT=${CODE_SERVER_PORT}
      - CODE_SERVER_PASSWORD=${CODE_SERVER_PASSWORD}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "${CODE_SERVER_PORT}:${CODE_SERVER_PORT}"
      - "4321:4321"
      - "8080:8080"
      - "13337:13337"
      # Pinokio ports
      - "7860:7860"
      - "8188:8188"
      - "42000:42000"
      - "42421:42421"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"