name: common
services:
  common:
    image: "${REGISTRY}/${GITHUB_ACTOR}/gold:latest"
    post_start:
      - command: install_extensions development python rust
    privileged: true
    restart: unless-stopped
    tty: true