name: convertx
services:
  convertx:
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - convertx_data:/app/data
    environment:
      ALLOW_UNAUTHENTICATED: true
      AUTO_DELETE_EVERY_N_HOURS: 0
volumes:
  convertx_data: