name: "npm proxy"
services:
  proxy:
    image: "${REGISTRY}/${GITHUB_ACTOR}/web:${VERSION}"
    container_name: "npm"
    hostname: npm
    ports:
      - "4873:4873"
    restart: unless-stopped
    tty: true